# Generated by Django 4.2.3 on 2024-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_certifyinginstitution_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="profiles",
            field=models.ManyToManyField(
                related_name="certificades", to="projects.profile"
            ),
        ),
    ]
